### ISSUE TITLE
building an image on docker hub gives exception

### ISSUE THREAD

**Issue by gijzelaerr** [docker/distribution#1179]
```
Encountered error: Traceback (most recent call last): File "/common/highland/utils.py", line 35, in
build_update_context yield File "/common/highland/monitor.py", line 137, in monitor if
self.build_finished(): File "/common/highland/monitor.py", line 111, in build_finished raise
Exception("Non-zero exit code: %r" % exit_code) Exception: Non-zero exit code: 1
```

https://hub.docker.com/r/radioastro/base/builds/btuqmpwab2qaap4vgdctsuz/

**Comment by stevvooe** [comment]
This is an issue with the hub. Please open a ticker at https://support.docker.com/.
