### ISSUE TITLE
Proxy registry crashes at start when there is no Internet connection

### ISSUE THREAD

**Issue by oiavorskyi** [docker/distribution#1435]
I want to use the local registry proxy instance to ensure that I could pull docker images from VirtualBox VM's even when my laptop does not have Internet connectivity. This is important when playing with automation of swarm clusters creation from scratch. After image has been pulled through proxy for the first time it should be pulled from proxy event when connectivity is absent.

This functionality works if I shut down Internet connectivity **after** starting registry proxy. However, if I shutdown the proxy, disconnect from Internet and then start it again the registry fails with following logs:

```
time="2016-02-06T16:19:14Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.3 instance.id=67d46eed-06af-4f85-ac76-df6801c333a2 version=v2.3.0
time="2016-02-06T16:19:14Z" level=info msg="redis not configured" go.version=go1.5.3 instance.id=67d46eed-06af-4f85-ac76-df6801c333a2 version=v2.3.0
time="2016-02-06T16:19:14Z" level=info msg="Starting upload purge in 26m0s" go.version=go1.5.3 instance.id=67d46eed-06af-4f85-ac76-df6801c333a2 version=v2.3.0
time="2016-02-06T16:19:14Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.3 instance.id=67d46eed-06af-4f85-ac76-df6801c333a2 version=v2.3.0
time="2016-02-06T16:19:14Z" level=info msg="Starting cached object TTL expiration scheduler..." go.version=go1.5.3 instance.id=67d46eed-06af-4f85-ac76-df6801c333a2 version=v2.3.0
panic: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 10.0.1.1:53: read udp 172.17.0.2:47095->10.0.1.1:53: i/o timeout

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7fb5100be100, 0xc82035b0e0, 0xc820368500, 0x7fb5100be100)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:260 +0x23b0
github.com/docker/distribution/registry.NewRegistry(0x7fb5100be140, 0xc82035b0e0, 0xc820368500, 0xc820368500, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:94 +0x2b0
github.com/docker/distribution/registry.glob.func1(0x1339b80, 0xc820362c80, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:57 +0x2b3
github.com/spf13/cobra.(*Command).execute(0x1339b80, 0xc82008e010, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x6e3
github.com/spf13/cobra.(*Command).Execute(0x1339b80, 0x0, 0x0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x180
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x23

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 23 [sleep]:
time.Sleep(0x16b373ef000)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0x7fb5100be180, 0xc8203d6840, 0x7fb5100c25f8, 0xc820361560, 0x7fb5100c2548, 0xc8203fd260, 0x2260ff9290000, 0x1380d00, 0x4e94914f0000)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:969 +0x1af
created by github.com/docker/distribution/registry/handlers.startUploadPurger
	/go/src/github.com/docker/distribution/registry/handlers/app.go:976 +0x885

goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [select]:
github.com/docker/distribution/notifications.(*Broadcaster).run(0xc8203c5ad0)
	/go/src/github.com/docker/distribution/notifications/sinks.go:80 +0x66c
created by github.com/docker/distribution/notifications.NewBroadcaster
	/go/src/github.com/docker/distribution/notifications/sinks.go:39 +0x100

goroutine 25 [select]:
github.com/docker/distribution/registry/proxy/scheduler.(*TTLExpirationScheduler).Start.func1(0xc820408620)
	/go/src/github.com/docker/distribution/registry/proxy/scheduler/scheduler.go:135 +0x2c6
created by github.com/docker/distribution/registry/proxy/scheduler.(*TTLExpirationScheduler).Start
	/go/src/github.com/docker/distribution/registry/proxy/scheduler/scheduler.go:154 +0x314
```

Apparently for some reason the registry do initial DNS lookup of proxied location(s) and dies if there is an error during this step.

**To reproduce:**

1. Ensure that there is no connectivity to central Docker repo
2. Start repository in the proxy mode

I use following registry configuration:

```
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
    remoteurl: https://registry-1.docker.io
```

**Comment by RichardScothern** [comment]
On startup the registry does a handshake with the upstream for authorization purposes which is not possible with no connection.   Generally the registry panics on configuration errors to prevent startup in an invalid state.

I will look into changing this so auth can be done lazily (on first pull).

**Comment by oiavorskyi** [comment]
@RichardScothern thank you for the reply. I assume that the credentials check will be done only when requested content is not cached and has to be retriever from the upstream, right? This should fully cover the offline scenario.

**Comment by mitchhh22** [comment]
I am experiencing the same crashloop when registry can't reach docker hub.

Is there a setting to prevent it from crashing and put it in an 'offline' mode? 
I would like the registry to serve the images it has cached even though it can reach out to docker hub at the time.

**Comment by mikef-phy** [comment]
This still appears to be a problem.  Why cant the server just run and host images without a connection to dockerhub?  Just fail the pull still serve the images.
