### ISSUE TITLE
Issue with docker registry v2

### ISSUE THREAD

**Issue by pavithra76** [docker/distribution#1440]
When i tried to pull docker image from docker registry v2 i get the following issue, any ideas?

Also when i check the registry image, its not returning all the images i set up. ANything that i am missing?

latest: Pulling from oracle-xe
23537abe4612: Pulling fs layer
e3b0c44298fc: Pulling fs layer
fed740cd76a2: Downloading [==================================================>] 27.76 MB/27.76 MB
41b9fc904a0b: Waiting
8487c9beba15: Waiting
587927d41688: Waiting
c2cddfc3d01d: Waiting
e3339bf2687e: Waiting
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 460, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 320, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 208, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 236, in ensure_image_exists
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 694, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: unsupported digest algorithm

**Comment by aaronlehmann** [comment]
Was this registry migrated from a v1 registry with a script?

I suggest trying to pull and repush the images with 1.9. This should cause them to use a supported digest algorithm.

**Comment by pavithra76** [comment]
It was working week back and all of a sudden its having that issue. 

I am new to dockers, how can i do that ?

**Comment by dmp42** [comment]
@pavithra76 we need at least some basic information about your docker, compose and registry version, if you updated anything recently, etc.

**Comment by pavithra76** [comment]
Thanks for the response.
Nothing changed in the configuration.
docker - Docker version 1.7.1, build 786b29d
registry version i belive its V2

Let me know if you need anything else ?

Thanks
Pavithra

**Comment by pavithra76** [comment]
I fixed it basically by pull and repush the images
