### ISSUE TITLE
error in code - Duplicated key 'interval' in struct configuration.TCPChecker

### ISSUE THREAD

**Issue by jantman** [docker/distribution#1742]
__UPDATE:__ see my next comment for the location of the bug.

I'm in the process of deploying the registry (image version 2.4.1) in EC2. I've configured it largely according to the documentation.

running (via systemd):
```
/usr/bin/docker run --rm --name docker-registry-v2 --publish 5000:5000 --volume /etc/docker_registry_config.yml:/etc/docker/registry/config.yml registry:2.4.1
```

``/etc/docker_registry_config.yml`` (addresses and secret obfuscated):

```
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: redis
    s3:
        region: us-east-1
        bucket: mybucket
        v4auth: true
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
    secret: mysecret
redis:
  addr: myredisaddr:6379
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
  tcp:
    - addr: myredisaddr:6379
      timeout: 3s
      interval: 10s
      threshold: 3

```

When run (via systemd, with docker logs going to journald), it exits with:

```
May 24 14:26:33 ip-10-142-0-131 systemd[1]: Started Docker Container Service for docker-registry-v2.
May 24 14:26:34 ip-10-142-0-131 docker[4703]: panic: Duplicated key 'interval' in struct configuration.TCPChecker [recovered]
May 24 14:26:34 ip-10-142-0-131 docker[4703]: panic: Duplicated key 'interval' in struct configuration.TCPChecker
May 24 14:26:34 ip-10-142-0-131 docker[4703]: goroutine 1 [running]:
May 24 14:26:34 ip-10-142-0-131 docker[4703]: panic(0xd24f00, 0xc82032cf10)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.handleErr(0xc8201994a0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/yaml.go:152 +0xdf
May 24 14:26:34 ip-10-142-0-131 docker[4703]: panic(0xd24f00, 0xc82032cf10)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /usr/local/go/src/runtime/panic.go:443 +0x4e9
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).mappingStruct(0xc8202dbc80, 0xc820336d20, 0xde14a0, 0xc82033c5d0, 0x199, 0xb8c020)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:606 +0xc1
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).mapping(0xc8202dbc80, 0xc820336d20, 0xde14a0, 0xc82033c5d0, 0x199, 0xde14a0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:513 +0xc9e
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc8202dbc80, 0xc820336d20, 0xde14a0, 0xc82033c5d0, 0x199, 0x199)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:292 +0x135
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).sequence(0xc8202dbc80, 0xc820336cc0, 0xbafae0, 0xc82006fd98, 0x197, 0xbafae0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:498 +0x2ad
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc8202dbc80, 0xc820336cc0, 0xbafae0, 0xc82006fd98, 0x197, 0xc82006fd98)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:294 +0x16c
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).mappingStruct(0xc8202dbc80, 0xc820336900, 0xde1260, 0xc82006fd68, 0x199, 0xb8bcc0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:626 +0x57d
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).mapping(0xc8202dbc80, 0xc820336900, 0xde1260, 0xc82006fd68, 0x199, 0xde1260)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:513 +0xc9e
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc8202dbc80, 0xc820336900, 0xde1260, 0xc82006fd68, 0x199, 0xc82006fd68)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:292 +0x135
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).mappingStruct(0xc8202dbc80, 0xc8203333e0, 0xe76ba0, 0xc82006fb80, 0x199, 0xb8c140)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:626 +0x57d
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).mapping(0xc8202dbc80, 0xc8203333e0, 0xe76ba0, 0xc82006fb80, 0x199, 0xe76ba0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:513 +0xc9e
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc8202dbc80, 0xc8203333e0, 0xe76ba0, 0xc82006fb80, 0x199, 0xc82001e900)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:292 +0x135
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).document(0xc8202dbc80, 0xc820333380, 0xe76ba0, 0xc82006fb80, 0x199, 0xc8201993d0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:304 +0xa3
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc8202dbc80, 0xc820333380, 0xe76ba0, 0xc82006fb80, 0x199, 0x199)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/decode.go:280 +0x5f
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/gopkg.in/yaml%2ev2.Unmarshal(0xc820291800, 0x2db, 0x600, 0xb8c140, 0xc82006fb80, 0x0, 0x0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/gopkg.in/yaml.v2/yaml.go:90 +0x2aa
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/configuration.(*Parser).Parse(0xc8202ddb90, 0xc820291800, 0x2db, 0x600, 0xb8bb40, 0xc82006f600, 0x0, 0x0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/configuration/parser.go:129 +0x328
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/configuration.Parse(0x7f8026aa42c8, 0xc82001e8d0, 0xc82001e8d0, 0x0, 0x0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/configuration/configuration.go:584 +0x32b
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/registry.resolveConfiguration(0xc8202d7f70, 0x1, 0x1, 0x0, 0x0, 0x0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/registry/registry.go:321 +0x1b2
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/registry.glob.func1(0x1428340, 0xc8202d7f70, 0x1, 0x1)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/registry/registry.go:37 +0xe7
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1428340, 0xc8202d7f20, 0x1, 0x1, 0x0, 0x0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x6d4
May 24 14:26:34 ip-10-142-0-131 docker[4703]: github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14284e0, 0x0, 0x0)
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x180
May 24 14:26:34 ip-10-142-0-131 docker[4703]: main.main()
May 24 14:26:34 ip-10-142-0-131 docker[4703]: /go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x23
May 24 14:26:34 ip-10-142-0-131 systemd[1]: docker-docker-registry-v2.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

I tried removing the ``interval`` element from the tcp health portion of the config, but get the same error. I'm really confused, as the health section was copied directly from [the documentation](https://github.com/docker/distribution/blob/master/docs/configuration.md#health).

Any assistance would be greatly appreciated, as this really seems like a bug to me.

**Comment by jantman** [comment]
The bug seems to be here: https://github.com/docker/distribution/blob/master/configuration/configuration.go#L239

in configuration.go, starting from line 240:
```
	// Timeout is the duration to wait before timing out the TCP connection
	Timeout time.Duration `yaml:"interval,omitempty"`
	// Interval is the duration in between checks
	Interval time.Duration `yaml:"interval,omitempty"`
```

**Comment by RichardScothern** [comment]
good catch @jantman

**Comment by jantman** [comment]
Thanks. It led to a bit of head-scratching for me until I looked at the code.
