### ISSUE TITLE
OSError: [Errno 2] No such file or directory: './registry._setup_database.lock'

### ISSUE THREAD

**Issue by EvertMDC** [docker/distribution#1750]
Hello,

I was trying to move from registry 2.1 to the latest build but it gives me the errors below.
Initially I was mapping the /var/lib/registry to my host to preserve the data and I imagined it did not like the transition. However when this was removed (only certificates are mapped now) it still gives me this error.
There does not seem to be an issue open for this. Come somebody shed some light on this?

```
[2016-05-27 15:40:20 +0000] [1] [INFO] Starting gunicorn 19.1.1
[2016-05-27 15:40:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2016-05-27 15:40:20 +0000] [1] [INFO] Using worker: gevent
[2016-05-27 15:40:20 +0000] [22] [INFO] Booting worker with pid: 22
[2016-05-27 15:40:20 +0000] [23] [INFO] Booting worker with pid: 23
[2016-05-27 15:40:20 +0000] [24] [INFO] Booting worker with pid: 24
[2016-05-27 15:40:20 +0000] [25] [INFO] Booting worker with pid: 25
27/May/2016:15:40:20 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:20 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:20 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:20 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:20 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:20 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:20 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:20 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:20 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:20 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:20 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:20 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:21 +0000 WARNING: Another process is creating the search database
27/May/2016:15:40:21 +0000 WARNING: Another process is creating the search database
27/May/2016:15:40:21 +0000 WARNING: DB is disconnected. Reconnect to it.
[2016-05-27 15:40:21 +0000] [22] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/__init__.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 86, in __init__
    self._setup_database()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 330, in wrapper
    os.remove(lock_path)
OSError: [Errno 2] No such file or directory: './registry._setup_database.lock'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 193, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 114, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/wsgi.py", line 27, in <module>
    from .search import *  # noqa
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/search.py", line 14, in <module>
    INDEX = index.load(cfg.search_backend.lower())
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/__init__.py", line 82, in load
    return db.SQLAlchemyIndex()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 86, in __init__
    self._setup_database()
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 330, in wrapper
    os.remove(lock_path)
OSError: [Errno 2] No such file or directory: './registry._setup_database.lock'
[2016-05-27 15:40:21 +0000] [22] [INFO] Worker exiting (pid: 22)
[2016-05-27 15:40:22 +0000] [25] [INFO] Worker exiting (pid: 25)
[2016-05-27 15:40:22 +0000] [24] [INFO] Worker exiting (pid: 24)
[2016-05-27 15:40:22 +0000] [23] [INFO] Worker exiting (pid: 23)
[2016-05-27 15:40:22 +0000] [1] [INFO] Shutting down: Master
[2016-05-27 15:40:22 +0000] [1] [INFO] Reason: Worker failed to boot.
[2016-05-27 15:40:22 +0000] [1] [INFO] Starting gunicorn 19.1.1
[2016-05-27 15:40:22 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2016-05-27 15:40:22 +0000] [1] [INFO] Using worker: gevent
[2016-05-27 15:40:22 +0000] [22] [INFO] Booting worker with pid: 22
[2016-05-27 15:40:22 +0000] [23] [INFO] Booting worker with pid: 23
[2016-05-27 15:40:22 +0000] [24] [INFO] Booting worker with pid: 24
[2016-05-27 15:40:22 +0000] [26] [INFO] Booting worker with pid: 26
27/May/2016:15:40:23 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:23 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:23 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:23 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:23 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:23 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:23 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:23 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:23 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
27/May/2016:15:40:23 +0000 WARNING: Cache storage disabled!
27/May/2016:15:40:23 +0000 WARNING: LRU cache disabled!
27/May/2016:15:40:23 +0000 DEBUG: Will return docker-registry.drivers.file.Storage
```

**Comment by dmcgowan** [comment]
The v2 registry does not require gunicorn so not sure I understand your setup of a 2.1 registry. I would encourage you to start with the deployment instructions specified here https://docs.docker.com/registry/deploying/.

**Comment by RichardScothern** [comment]
@EvertMDC unfortunately the `latest` tag still points to the v1 registry.  This will be changed with the next release but for now `registry:2` will give you the latest (2.4.1) registry image.
