### ISSUE TITLE
panic: Swift authentication failed: Authorization Failed

### ISSUE THREAD

**Issue by winggundamth** [docker/distribution#1879]
This is my config.yml

```yml
version: 0.1
log:
  level: debug
storage:
  cache:
    blobdescriptor: inmemory
  swift:
    username: registry
    password: CHANGEME
    authurl: https://keystone.example.com/v3
    container: registry
    tenant: ops
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

When I do docker run registry:2.5.0 I always got this error

```
panic: Swift authentication failed: Authorization Failed

goroutine 1 [running]:
panic(0xd88060, 0xc82017c450)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/distribution/registry/handlers.NewApp(0x7eff6ed676d0, 0xc820329d40, 0xc820356580, 0x7eff6ed676d0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:121 +0x619
github.com/docker/distribution/registry.NewRegistry(0x7eff6ed67710, 0xc820329d40, 0xc820356580, 0xc820356580, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x2b0
github.com/docker/distribution/registry.glob.func1(0x14ccdc0, 0xc820307cd0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x2a9
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x14ccdc0, 0xc820307c80, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x6d4
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14ccf60, 0x0, 0x0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x180
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x23
```

I'm using OpenStack Mitaka right now. When I check on keystone log I got this (Keystone has run behind HAProxy)

```
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:54.169245 2016-08-02 22:44:54.168 16158 INFO keystone.common.wsgi [req-1c17fa14-13db-4657-9d01-ccf03b07916a eaa9a2b3d4874c559878721012ba35fc 24f386a782ad4563a4339f4c8b094f45 - default default] OPTIONS http://infra1-keystone-conta
iner-98469d26:35357/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:55.257736 2016-08-02 22:44:55.257 16163 INFO keystone.common.wsgi [re
q-75274065-148f-4a95-9705-fa394af08dc1 21f581f55d104761842f1a22cb89b09a 24f386a782ad4563a4339f4c8b094f45 - default default] OPTIONS http://infra1-keystone-container-98469d26:35357/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:55.963122 2016-08-02 22:44:55.962 16118 INFO keystone.common.wsgi [req-195c5193-7b2a-448c-9b38-4681bb6a901c - - - - -] OPTIONS http://infra1-keystone-container-98469d26:5000/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:56.375209 2016-08-02 22:44:56.374 16139 INFO keystone.common.wsgi [req-c5f64b90-ff9d-4a00-8b40-a5b024460f44 - - - - -] OPTIONS http://infra1-keystone-container-98469d26:5000/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:56.661346 2016-08-02 22:44:56.660 16122 INFO keystone.common.wsgi [req-3e515914-71be-4edf-b451-ade9d922059b - - - - -] POST https://keystone.example.com/v3/auth/tokens
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:56.677288 2016-08-02 22:44:56.675 16122 WARNING keystone.common.wsgi 
[req-3e515914-71be-4edf-b451-ade9d922059b - - - - -] Authorization failed. The request you have made requires authentication. from 172.27.5.11
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:57.612004 2016-08-02 22:44:57.611 16131 INFO keystone.common.wsgi [re
q-747a0139-3944-4525-930e-83210a7a1abd - - - - -] OPTIONS http://infra1-keystone-container-98469d26:5000/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:57.620711 2016-08-02 22:44:57.620 16114 INFO keystone.common.wsgi [re
q-1be36eb0-6870-4389-9a67-eb5ea3e495d6 - - - - -] OPTIONS http://infra1-keystone-container-98469d26:5000/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:58.083769 2016-08-02 22:44:58.083 16162 INFO keystone.common.wsgi [re
q-f5461862-fc1e-4c21-af10-265ed6e66ae9 eaa9a2b3d4874c559878721012ba35fc 24f386a782ad4563a4339f4c8b094f45 - default default] OPTIONS http://infra1-keystone-conta
iner-98469d26:35357/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:44:58.790449 2016-08-02 22:44:58.789 16128 INFO keystone.common.wsgi [re
q-c780a4d9-c41e-46e2-816f-dbae08711b11 0959bfdc2ccb67e18a8ab29808eb0365f40ab6d49481730aaac14da423a96be9 - - c731f4bdb89b49debfceaf18766b4e7f -] OPTIONS http://i
nfra1-keystone-container-98469d26:5000/
Aug  2 22:45:00 infra1-keystone-container-98469d26 keystone-apache-error: 2016-08-02 22:45:00.632881 2016-08-02 22:45:00.632 16122 INFO keystone.common.wsgi [re
q-3e515914-71be-4edf-b451-ade9d922059b - - - - -] OPTIONS http://infra1-keystone-container-98469d26:5000/
```

Anyway I can do more debugging to see what causing Swift authentication failed: Authorization Failed?

**Comment by RichardScothern** [comment]
Can you hit the auth server directly (with curl) using your credentials and get a successful authorization?  If so, does the request match what the registry is sending?

**Comment by winggundamth** [comment]
I can confirm that using curl and swift list get successful. But I don't
know how to see what registry sending to keystone. Do you have any idea to
check on this?

**Comment by RichardScothern** [comment]
It won't be easy.  You could use wireshark or similar to see which calls are being made.  Otherwise, adding some debug statements to the driver would work.

Have you seen this bug with previous versions of the registry?

**Comment by winggundamth** [comment]
This is my first time try to use Swift as storage driver so I never do this
before.

**Comment by winggundamth** [comment]
So it turns out that I confuse between availability zone and region. After fix the correct region, it works.
