### ISSUE TITLE
docker on windows 10 pro cannot run Linux containers

### ISSUE THREAD

**Issue by kirill-linnik** [docker/distribution#2438]
Dear Docker team,

My Docker Windows installation was running smoothly till today, when I've got:

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '<...>' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```
Hyper-V is switched on (re-checked), I have the latest version too and diagnostic ID is: 2C32C722-7D00-45CD-8C7A-71E6B4C7349B/2017-11-03_13-41-40

BTW, there is no such path as C:\gopath on my machine.

**Comment by dmcgowan** [comment]
Please file an issue at https://github.com/docker/for-win
