### ISSUE TITLE
Error while taking UCP backup

### ISSUE THREAD

**Issue by Sheshagiri-RVBD** [docker/distribution#2676]
While taking back of my UCP node I see the following error.

```root@docker:~# docker container run --log-driver none --rm -i     --name ucp     -v /var/run/docker.sock:/var/run/docker.sock     docker/ucp:3.0.2    backup --interactive > backup-v2.tar
INFO[0000] Your engine version 17.06.2-ee-16, build 9ef4f0a (4.4.0-112-generic) is compatible with UCP 3.0.2 (736cf3c)
INFO[0000] We're about to temporarily stop all local UCP containers for UCP ID: isf0dbkbykcrvkiu96yshx1eg
Do you want proceed with the backup? (y/n): y
INFO[0002] Temporarily stopping local UCP containers to ensure a consistent backup
INFO[0081] Backing up internal KV store
INFO[0000] Beginning backup
ERRO[0000] Error: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc420540f18, 0x1710720, 0x248bd40)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
main.main.func6()
        /go/src/github.com/docker/orca/bootstrap/main.go:795 +0x5a
panic(0x1710720, 0x248bd40)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/docker/orca/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc420541c30)
        /go/src/github.com/docker/orca/vendor/github.com/codegangsta/cli/app.go:472 +0x2c8
panic(0x1710720, 0x248bd40)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/docker/orca/bootstrap/backup.loadConfigData(0x2446280, 0xc4201e4a80, 0xc4203504e0, 0x2f, 0x193c44a, 0xa, 0x1, 0x0, 0x9f1, 0x9f3, ...)
        /go/src/github.com/docker/orca/bootstrap/backup/run.go:480 +0x42e
github.com/docker/orca/bootstrap/backup.backupUCPConfigs(0x2446280, 0xc4201e4a80, 0xc420084480, 0x1a0f, 0x13fa)
        /go/src/github.com/docker/orca/bootstrap/backup/run.go:453 +0x212
github.com/docker/orca/bootstrap/backup.runPhase2(0xc42047edc0, 0xc42036ad00, 0xc420406480, 0xf, 0x11, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/orca/bootstrap/backup/run.go:424 +0x9ca
github.com/docker/orca/bootstrap/backup.backup(0xc42047edc0, 0xc420429320, 0xc42036c450, 0xc4204a7800)
        /go/src/github.com/docker/orca/bootstrap/backup/run.go:94 +0x1ba
github.com/docker/orca/bootstrap/backup.Run(0xc42047edc0)
        /go/src/github.com/docker/orca/bootstrap/backup/run.go:512 +0x2f
reflect.Value.call(0x1665d00, 0x19deae0, 0x13, 0x192870c, 0x4, 0xc4204a7bd0, 0x1, 0x1, 0xc4204a7b50, 0x18f1800, ...)
        /usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x1665d00, 0x19deae0, 0x13, 0xc4204a7bd0, 0x1, 0x1, 0xc42047edc0, 0x7f8e41424628, 0x0)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/docker/orca/vendor/github.com/codegangsta/cli.HandleAction(0x1665d00, 0x19deae0, 0xc42047edc0, 0x0, 0x0)
        /go/src/github.com/docker/orca/vendor/github.com/codegangsta/cli/app.go:481 +0x180
github.com/docker/orca/vendor/github.com/codegangsta/cli.Command.Run(0x192a981, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x195b158, 0x25, 0x0, ...)
        /go/src/github.com/docker/orca/vendor/github.com/codegangsta/cli/command.go:186 +0x9ed
github.com/docker/orca/vendor/github.com/codegangsta/cli.(*App).Run(0xc42045d200, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/docker/orca/vendor/github.com/codegangsta/cli/app.go:235 +0x57d
main.main()
        /go/src/github.com/docker/orca/bootstrap/main.go:800 +0x552b

INFO[0083] Resuming stopped UCP containers
root@docker:~# ls -ltr
total 172
-rw-r--r-- 1 root root 174080 Aug 14 14:55 backup-v2.tar
root@docker:~#```

As you can see the in above snippet inspite of the error backup archive got created. Not sure if that has all the configuration backedup.

Following is the system configuration

```root@docker:~# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:41:28 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:40:18 2018
  OS/Arch:      linux/amd64
  Experimental: false

root@docker:~# docker container run --log-driver none --rm -i     --name ucp     -v /var/run/docker.sock:/var/run/docker.sock     docker/ucp:3.0.2    --version
docker run --rm -it \
        -v /var/run/docker.sock:/var/run/docker.sock \
        docker/ucp \
         version 3.0.2 (736cf3c)
root@docker:~#```

**Comment by manishtomar** [comment]
This issue is related to Docker Enterprise and should be filed via regular support channel. Can you please email it to support@docker.com?
