### ISSUE TITLE
PUT on blob with tarsum hangs after merge of #238

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#269]
During testing of the registry v2.0.0-alpha.3, against a filesystem root, we found that a PUT request to finalize a blob upload would hang when using tarsum as the incoming blob digest. The same behavior does not happen when using sha256 digests.

The problem was bisected to occurring between these two commits:

| Commit  | Behavior                |
|-------------|--------------------------|
| 81a0304 | PUT with tarsum works |
| e3dd701 | PUT with tarsum hangs |

This is likely a regression from the changes in #238.

A dump of the goroutines on the running instance yield the follow stack trace:

```
goroutine 98 [semacquire, 2 minutes]:
sync.(*Cond).Wait(0xc20807e068)
	/usr/src/go/src/sync/cond.go:62 +0x9e
io.(*pipe).write(0xc20807e000, 0xc208166000, 0x800, 0x8000, 0x0, 0x7f46a038ce80, 0xc20802a150)
	/usr/src/go/src/io/pipe.go:94 +0x244
io.(*PipeWriter).Write(0xc208042070, 0xc208166000, 0x800, 0x8000, 0x0, 0x0, 0x0)
	/usr/src/go/src/io/pipe.go:161 +0x5b
github.com/docker/distribution/digest.(*tarsumVerifier).Write(0xc208086810, 0xc208166000, 0x800, 0x8000, 0x800, 0x0, 0x0)
	/go/src/github.com/docker/distribution/digest/verifiers.go:129 +0x5c
io.(*teeReader).Read(0xc208156260, 0xc208166000, 0x8000, 0x8000, 0x800, 0x7f46a038ce80, 0xc20802a100)
	/usr/src/go/src/io/io.go:497 +0x112
io.Copy(0x7f46a0398c10, 0xc20807cc80, 0x7f46a0398be8, 0xc208156260, 0x200000, 0x0, 0x0)
	/usr/src/go/src/io/io.go:362 +0x1f6
github.com/docker/distribution/digest.FromReader(0x7f46a0398be8, 0xc208156260, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/digest/digest.go:74 +0xa2
github.com/docker/distribution/registry/storage.(*layerUploadController).validateLayer(0xc20807c080, 0xc20805b080, 0x51, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/layerupload.go:107 +0x291
github.com/docker/distribution/registry/storage.(*layerUploadController).Finish(0xc20807c080, 0xc20805b080, 0x51, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/layerupload.go:52 +0x23d
github.com/docker/distribution/notifications.(*layerUploadListener).Finish(0xc208156000, 0xc20805b080, 0x51, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/notifications/listener.go:143 +0x9c
github.com/docker/distribution/registry/handlers.(*layerUploadHandler).PutLayerUploadComplete(0xc208149420, 0x7f46a0394628, 0xc208156060, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/registry/handlers/layerupload.go:203 +0x4d3
github.com/docker/distribution/registry/handlers.*layerUploadHandler.PutLayerUploadComplete·fm(0x7f46a0394628, 0xc208156060, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/registry/handlers/layerupload.go:31 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20802b6a0, 0x7f46a0394628, 0xc208156060, 0xc20801f2b0)
	/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/handlers.MethodHandler.ServeHTTP(0xc208086f90, 0x7f46a0394628, 0xc208156060, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/gorilla/handlers/handlers.go:38 +0xbb
github.com/docker/distribution/registry/handlers.func·004(0x7f46a0394628, 0xc208156060, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/registry/handlers/helpers.go:30 +0x112
net/http.HandlerFunc.ServeHTTP(0xc208156040, 0x7f46a0394628, 0xc208156060, 0xc20801f2b0)
	/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/docker/distribution/registry/handlers.func·003(0x7f46a03941e0, 0xc2080eb340, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:257 +0xbf1
net/http.HandlerFunc.ServeHTTP(0xc2080f0ae0, 0x7f46a03941e0, 0xc2080eb340, 0xc20801f2b0)
	/usr/src/go/src/net/http/server.go:1265 +0x41
github.com/gorilla/mux.(*Router).ServeHTTP(0xc208044690, 0x7f46a03941e0, 0xc2080eb340, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:98 +0x297
github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc208040820, 0x7f46a03941e0, 0xc2080eb340, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:181 +0xde
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x7f46a0391170, 0xc208042008, 0x7f46a0392e40, 0xc208040820, 0x7f46a0394138, 0xc20808d720, 0xc20801f2b0)
	/go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/gorilla/handlers/handlers.go:88 +0x1be
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc2080f0b80, 0x7f46a0394138, 0xc20808d720, 0xc20801f2b0)
	<autogenerated>:15 +0xbe
net/http.serverHandler.ServeHTTP(0xc20805ab40, 0x7f46a0394138, 0xc20808d720, 0xc20801f2b0)
	/usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc20808d540)
	/usr/src/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/src/go/src/net/http/server.go:1751 +0x35e
```

Given the above, this is likely a problem with the implementation of `digest.NewDigestVerifier`. The goroutine is blocking on a write to the pipe, which should be answered by a read in the other goroutine.

**Comment by stevvooe** [comment]
Minimal reproducing case:

```
package main

import (
	"io"
	"log"
	"os"

	"github.com/docker/distribution/digest"
)

func main() {
	verifier, err := digest.NewDigestVerifier(digest.Digest(os.Args[1]))
	if err != nil {
		log.Fatalln("error creating verifier: %v", err)
	}

	nn, err := io.Copy(verifier, os.Stdin)
	if err != nil {
		log.Fatalln("error copying to verifier: %v", err)
	}

	log.Fatalln("verified %d bytes", nn)

	if !verifier.Verified() {
		log.Fatalln("not verified")
	}

	log.Fatalln("verified")
}
```

Running with incoming tarsum file results in deadlock:

```
$ curl -sI https://registry-1.docker.io/v2/library/ubuntu/blobs/tarsum.dev+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 | go run tsb.go tarsum.dev+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.(*Cond).Wait(0x2082e4068)
	/usr/local/go/src/sync/cond.go:62 +0x9e
io.(*pipe).write(0x2082e4000, 0x2082e8000, 0x29b, 0x8000, 0x0, 0x220827d780, 0x2082a00e0)
	/usr/local/go/src/io/pipe.go:94 +0x244
io.(*PipeWriter).Write(0x2082c4068, 0x2082e8000, 0x29b, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/go/src/io/pipe.go:161 +0x5b
github.com/docker/distribution/digest.(*tarsumVerifier).Write(0x2082aa6c0, 0x2082e8000, 0x29b, 0x8000, 0x29b, 0x0, 0x0)
	/Users/sday/go/src/github.com/docker/distribution/digest/verifiers.go:129 +0x5c
io.Copy(0x2208281bb8, 0x2082aa6c0, 0x2208281b90, 0x2082c4000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:364 +0x278
main.main()
	/Users/sday/go/src/github.com/docker/distribution/tsb.go:17 +0x226
exit status 2
```

**Comment by dmcgowan** [comment]
This issue is caused by the content being gzipped, nothing is decompressing the data before reading it as a tar.
