### ISSUE TITLE
Registry caching proxy with authorization not working 

### ISSUE THREAD

**Issue by anannaya** [docker/distribution#2811]
Hi,

**SETUP:**
I am trying configure the registry cache with registry:2 latest image. I have a JFrog docker registry which is hosted outside the lab network.  I am trying to create the registry cache which is in one of the lab machine(firewall opened) So that same cache registry be used by other lab machines.

![image](https://user-images.githubusercontent.com/19487932/51025164-53c00a80-15b1-11e9-81da-499333e35f47.png)

Below command is used to bring up the registry-cache(lab machine)(firewall opened)
`docker run -td --net=host -v /registry-mirror/config.yml:/etc/docker/registry/config.yml -v /registry-mirror:/var/lib/registry --name registry-mirror dockerregistry.ims.nokia.com:6000/nokia/imsdev/registry:2`

Config file:
`http:
  addr: :7000
  net: tcp
  host: https://dockerregistry.ims.nokia.com:7000
  relativeurls: true
  tls:
    certificate: /var/lib/registry/certs/domain.crt
    key: /var/lib/registry/certs/domain.key
  headers:
    X-Content-Type-Options: [nosniff]
proxy:
  remoteurl: https://ims-docker-local.bhisoj70.apac.nsn-net.net
  username: anannaya
  password: xxxxxxxxxxxx
`
LOgs:
{{{
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.11.2 instance.id=71be4514-9b50-4b9e-af33-5ad65d567c7d service=registry version=v2.7.0
INFO[0000] redis not configured                          go.version=go1.11.2 instance.id=71be4514-9b50-4b9e-af33-5ad65d567c7d service=registry version=v2.7.0
INFO[0000] Starting upload purge in 43m0s                go.version=go1.11.2 instance.id=71be4514-9b50-4b9e-af33-5ad65d567c7d service=registry version=v2.7.0
INFO[0000] using inmemory blob descriptor cache          go.version=go1.11.2 instance.id=71be4514-9b50-4b9e-af33-5ad65d567c7d service=registry version=v2.7.0
DEBU[0000] filesystem.Stat("/scheduler-state.json")      go.version=go1.11.2 instance.id=71be4514-9b50-4b9e-af33-5ad65d567c7d service=registry trace.duration=40.777µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Stat" trace.id=d9177900-72b4-444d-8acd-29b1e3f5b4be trace.line=155 version=v2.7.0
INFO[0000] Starting cached object TTL expiration scheduler...  go.version=go1.11.2 instance.id=71be4514-9b50-4b9e-af33-5ad65d567c7d service=registry version=v2.7.0
panic: Get https://ims-docker-local.bhisoj70.apac.nsn-net.net/v2/: dial tcp 10.135.150.72:443: i/o timeout

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0xefe940, 0xc0003c80c0, 0xc000454a80, 0x0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:323 +0x290b
github.com/docker/distribution/registry.NewRegistry(0xefe940, 0xc0003c80c0, 0xc000454a80, 0xc000454a80, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:105 +0x1dc
github.com/docker/distribution/registry.glob..func1(0x15972c0, 0xc000482080, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:63 +0x187
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x15972c0, 0xc000482040, 0x1, 0x1, 0x15972c0, 0xc000482040)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x1597460, 0xc000277f88, 0xc0000ee058)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d

}}}

**Comment by manishtomar** [comment]
Your logs clearly state the problem (did you see them?):
```
panic: Get https://ims-docker-local.bhisoj70.apac.nsn-net.net/v2/: dial tcp 10.135.150.72:443: i/o timeout
```
Registry cannot connect to the remote host.

**Comment by anannaya** [comment]
@manishtomar  I created the sample container on same machine .. tried using docker-py module. login works properly. Is there any way i can get the return code of rest query. ??

**Comment by anannaya** [comment]
@manishtomar  Sorry some confusion, I have to reach **ims-docker-local.bhisoj70.apac.nsn-net.net**
jfrog registry via https proxy . Will it work if i pass http_proxy and https_proxy as a environment variables ?

**Comment by anannaya** [comment]
@manishtomar  thank you so much , I fixed the problem by passing environment variable. Happy weekend.
