### ISSUE TITLE
Crash in registry/handlers.startUploadPurger()

### ISSUE THREAD

**Issue by hinesmr** [docker/distribution#2820]
Greetings, I use the docker container image `registry:2` against an S3-compatible digitalocean object storage bucket like this:

  $ docker run registry -e REGISTRY_STORAGE=s3 -e REGISTRY_STORAGE_S3_REGIONENDPOINT=nyc3.digitaloceanspaces.com registry:2  
  $ # credential examples omitted for brevity

The registry crashes very deterministically when it attempts some kind of cleanup routine? (purge uploads?) It's so deterministic, it happens *precisely* after the number of minutes show in the log message `Starting upload purge in 29m0s` in this case.

Is this a known issue?

Example logs:
```
WARN[0000] No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable.  go.version=go1.11.2 instance.id=c1299382-0539-4ef2-bb77-669c6d4003ca service=registry version=v2.7.0
INFO[0000] redis not configured                          go.version=go1.11.2 instance.id=c1299382-0539-4ef2-bb77-669c6d4003ca service=registry version=v2.7.0
INFO[0000] Starting upload purge in 29m0s                go.version=go1.11.2 instance.id=c1299382-0539-4ef2-bb77-669c6d4003ca service=registry version=v2.7.0
INFO[0000] listening on [::]:5000                        go.version=go1.11.2 instance.id=c1299382-0539-4ef2-bb77-669c6d4003ca service=registry version=v2.7.0
INFO[1740] PurgeUploads starting: olderThan=2019-01-09 16:06:39.443167626 +0000 UTC m=-603059.971436602, actuallyDelete=true 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xba6c5d]

goroutine 11 [running]:
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc0000aa400, 0xc000284001, 0xc000839998)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x9d
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00000c720, 0x7fdf630cf1b8, 0xc0001ee310, 0xc00045e2d0, 0xc000839a98, 0x0, 0x0, 0x0, 0x1, 0x2)
        /go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc0002e5680, 0xefec00, 0xc0001ee2a0, 0xc000839b58, 0xc000830481, 0x20, 0xdc5475, 0x1, 0xc000358fc0, 0x0, ...)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc0002e5680, 0xefec00, 0xc0001ee2a0, 0xc0001bc880, 0x20, 0xc000358fc0, 0x2, 0x0)
        /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc0003a5af0, 0xefec00, 0xc0001ee2a0, 0xc0001bc880, 0x20, 0xc000358fc0, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
github.com/docker/distribution/registry/storage.getOutstandingUploads(0xefed40, 0xc0003acdc0, 0xf0a2c0, 0xc0003a5af0, 0x2, 0xc000094d40, 0xc000094e10, 0x808d3e)
        /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x236
github.com/docker/distribution/registry/storage.PurgeUploads(0xefed40, 0xc0003acdc0, 0xf0a2c0, 0xc0003a5af0, 0xbf05a4e3da6a338a, 0xfffddb85289fcfc6, 0x15a5680, 0xc000051701, 0xe09608, 0xc0001e3680, ...)
        /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x163
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0xf0ddc0, 0xc0002673b0, 0xefed40, 0xc0003acdc0, 0xf0a2c0, 0xc0003a5af0, 0x2260ff9290000, 0x0, 0x4e94914f0000)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:1071 +0x221
created by github.com/docker/distribution/registry/handlers.startUploadPurger
        /go/src/github.com/docker/distribution/registry/handlers/app.go:1064 +0x2e9
```

**Comment by manishtomar** [comment]
From the crash it looks like the S3 compatible service is not responding correctly. The S3 driver uses aws go sdk which provides pointers to structs that are expected to be there. In this case the pointer seems to be invalid which shows there is some incompatibility between the service and the sdk. I would recommend trying the go sdk directly on digitalocean object first.

**Comment by manishtomar** [comment]
In this case it looks like `objects` was `nil` at https://github.com/docker/distribution/blob/b1fd12d0c173a11f402cdf3ed725fc7e7b2a2553/registry/storage/driver/s3-aws/s3.go#L973

**Comment by robbat2** [comment]
Ceph RGW (as used by DigitalOcean) does NOT  implement the ListObjects v2 support.

The S3 client SHOULD expect to handle a ListObjects v1 response when passing the ListObjects v2 query parameter `list-type=2`.

**Comment by hinesmr** [comment]
@manishtomar Could we get support on the client side for the behavior that @robbat2 described?

**Comment by manishtomar** [comment]
@hinesmr Since its not a problem when talking to actual S3 service I doubt any of us will be interested in looking into it. We will be glad to review PRs if you find problem though.

**Comment by hinesmr** [comment]
@manishtomar I think you misunderstood. This is indeed a problem with the client when talking to the S3 service. We (DigitalOcean) follow the S3 protocol, but specifically V1 of the protocol. The client should be capable of handling V1 as my colleague @robbat2 described. We returned a V1 response when instead the client processed it as a V2 response. That's incorrect.

**Comment by hinesmr** [comment]
Thanks a lot @hrak and @manishtomar
