### ISSUE TITLE
Storage initialization problems cause panic with stack trace

### ISSUE THREAD

**Issue by dmage** [docker/distribution#3154]
When the registry cannot initialize a storage driver, it panics.

```
panic: Put https://<REDACTED>.blob.core.windows.net/<REDACTED>?restype=container: dial tcp: i/o timeout

goroutine 1 [running]:
...
```

Some users tend to blame software if they see a stack trace. It's better to give a helpful error message with indications that configuration may need to be updated.

**Comment by invidian** [comment]
Same happens when given malformed Azure storage credentials:
```
goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0xff8500, 0xc000479770, 0xc00047a700, 0x0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:127 +0x2dfd
github.com/docker/distribution/registry.NewRegistry(0xff8500, 0xc000478ff0, 0xc00047a700, 0xc00047a700, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:161 +0x1c5
github.com/docker/distribution/registry.glob..func1(0x1532be0, 0xc0004607a0, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:119 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1532be0, 0xc000460760, 0x1, 0x1, 0x1532be0, 0xc000460760)
        /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x1bc
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x1532d80, 0xd36d60, 0xc000082058)
        /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2bf
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
panic: azure: malformed storage account key: illegal base64 data at input byte 0
```
