### ISSUE TITLE
Not able to run registry:2 on CoreOS alpha 752.1

### ISSUE THREAD

**Issue by mindnuts** [docker/distribution#826]
Hi,

I am trying to run registry V2 on CoreOS.

```sh
$ docker -v
Docker version 1.7.1, build 786b29d-dirty
```

 I launch the service on cli like this:

```sh
$ docker run --name docker-registry -d -p 5000:5000 -e "REGISTRY_STORAGE=s3" -e "REGISTRY_STORAGE_S3_REGION=eu-west-1" -e "REGISTRY_STORAGE_S3_BUCKET=docker-repo" -e "REGISTRY_STORAGE_S3_ACCESSKEY=xxx" -e "REGISTRY_STORAGE_S3_SECRETKEY=xxx"  registry:2    
```
When i inspect the list of containers, i see this container has crashed

```sh
$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS                     PORTS               NAMES
7f9a52d07c04        registry:2                  "registry cmd/regist   4 seconds ago       Exited (2) 2 seconds ago                       docker-registry     
52ecae119b1b        xx/abc   "node /src/src/index   2 hours ago         Up 2 hours                                     abc-connect      

```

And the logs from the container:
```sh
$ docker logs 7f9a52d07c04
panic: Access Denied

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7fa0bfa55a90, 0xc2080c1890, 0xc20802b9d0, 0x3, 0xc20802ba08, 0x5, 0x0, 0x0, 0xc2080c0480, 0xa5e630, ...)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:81 +0x5eb
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:62 +0x439

goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc2080a7c30)
	/usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc2080a7c30)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc

```

Not sure what is that i am doing wrong. I tried to search similar for issues on google but nothing was found. Can someone please help me?

Regards
M

**Comment by aaronlehmann** [comment]
It looks like this panic is related to accessing the backend storage. Can you confirm that the S3 parameters are correct? It may also be a good idea to try out using the filesystem as a backend store, just to make sure it starts up correctly in that mode.

**Comment by aaronlehmann** [comment]
It's possible that this is related to v4 auth. Apparently v2 auth is better-tested. You can try disabling the v4auth configuration parameter. See https://github.com/docker/distribution/issues/802 and https://groups.google.com/a/dockerproject.org/forum/?utm_medium=email&utm_source=footer#!msg/distribution/Cul5Gh_JsPA/GEU5rN5hJgAJ

**Comment by mindnuts** [comment]
@aaronlehmann it was indeed an issue with backend storage. The bucket was wrongly configured. Thanks for helping me with that. However i am facing another issue. After i change the bucket i am able to run the docker registery v2 from cli, but if i convert that to a systemd unit file it fails with error:

```sh
Aug 07 09:48:08 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:08 core-01 docker[2205]: docker-registry
Aug 07 09:48:08 core-01 docker[2216]: docker-registry
Aug 07 09:48:08 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:08 core-01 docker[2228]: 4a825be6a7b325d43f93b348fecab59638134f8c26931e99636d92f6ec25a99f
Aug 07 09:48:09 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:09 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:09 core-01 docker[2296]: docker-registry
Aug 07 09:48:09 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:09 core-01 docker[2303]: f65e23d5b9c1ff7b71896225606ddc5970d7bceb482453f11697731d93d6a62c
Aug 07 09:48:19 core-01 docker[2343]: docker-registry
Aug 07 09:48:19 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:19 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:19 core-01 docker[2364]: docker-registry
Aug 07 09:48:19 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:19 core-01 docker[2385]: 7d4c4334a46cfc5fb0173104a085b2325cc281c4b69a1b47814b0650b684a325
Aug 07 09:48:20 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:20 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:20 core-01 docker[2444]: docker-registry
Aug 07 09:48:20 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:20 core-01 docker[2458]: e39e5efd419ecbba6d081a398ed2c1ca959e203947bcc21fe652e346c116febf
Aug 07 09:48:20 core-01 docker[2498]: docker-registry
Aug 07 09:48:20 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:20 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:20 core-01 docker[2521]: docker-registry
Aug 07 09:48:20 core-01 docker[2529]: docker-registry
Aug 07 09:48:20 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:20 core-01 docker[2539]: cee5f779d11cd16f667eb8cfa3c03473fcd4638795e5604055a91d1786ab7e13
Aug 07 09:48:20 core-01 docker[2578]: docker-registry
Aug 07 09:48:21 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:21 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:21 core-01 docker[2597]: docker-registry
Aug 07 09:48:21 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:21 core-01 docker[2621]: e0dbf7ab53c00ec424672bd01eae0188c2a7eef1178d469fca53198b7fadc799
Aug 07 09:48:21 core-01 docker[2663]: docker-registry
Aug 07 09:48:21 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:21 core-01 systemd[1]: Starting Local Docker registry Service...
Aug 07 09:48:21 core-01 docker[2674]: docker-registry
Aug 07 09:48:21 core-01 docker[2685]: docker-registry
Aug 07 09:48:21 core-01 systemd[1]: Started Local Docker registry Service.
Aug 07 09:48:21 core-01 docker[2691]: d5ff45e1d4193d4ebcab9c7aab86a09dfbbaa150f52eb2941e9c95e0c93fa665
Aug 07 09:48:22 core-01 systemd[1]: docker-registry.service: Service hold-off time over, scheduling restart.
Aug 07 09:48:22 core-01 systemd[1]: docker-registry.service: Start request repeated too quickly.
Aug 07 09:48:22 core-01 systemd[1]: Failed to start Local Docker registry Service.
Aug 07 09:48:22 core-01 systemd[1]: docker-registry.service: Unit entered failed state.
Aug 07 09:48:22 core-01 systemd[1]: docker-registry.service: Failed with result 'start-limit'.
```

The unit file:

```sh
[Unit]
Description=Local Docker registry Service
After=etcd.service
After=docker.service
Requires=etcd.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
RestartSec=10s
EnvironmentFile=/etc/environment
User=core

ExecStartPre=-/usr/bin/docker kill docker-registry
ExecStartPre=-/usr/bin/docker rm docker-registry

ExecStart=/usr/bin/docker run --name docker-registry \
  -p ${COREOS_PRIVATE_IPV4}:5000:5000  \
  -e "REGISTRY_STORAGE=s3" \
  -e "REGISTRY_STORAGE_S3_REGION=eu-west-1" \
  -e "REGISTRY_STORAGE_S3_BUCKET=docker-repo" \
  -e "REGISTRY_STORAGE_S3_ACCESSKEY=xxx" \
  -e "REGISTRY_STORAGE_S3_SECRETKEY=xxxxxxx" \
  registry:2

ExecStop=/usr/bin/docker stop docker-registry
```

Best regards
M

**Comment by dmp42** [comment]
Hi there @mindnuts 

Do you have a specific reason not to use the official docker image for the registry? (`docker run registry:2` should do)

This is the recommended way to use it.

If you really want to wrap it into systemd, we can certainly accept a contribution into `contrib/` - but it's not a scenario we are committed to support/maintain for now.

**Comment by stevvooe** [comment]
@mindnuts "Access Denied" is an error from the s3 driver. Confirm that you have properly configured the s3 credentials and have the appropriate access.

**Comment by mindnuts** [comment]
Hi @dmp42 If you notice my unit file i am indeed running the official docker image. Pasting my unit file here again for reference.

```sh
[Unit]
Description=Local Docker registry Service
After=etcd.service
After=docker.service
Requires=etcd.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
RestartSec=10s
EnvironmentFile=/etc/environment
User=core

ExecStartPre=-/usr/bin/docker kill docker-registry
ExecStartPre=-/usr/bin/docker rm docker-registry

ExecStart=/usr/bin/docker run --name docker-registry \
  -p ${COREOS_PRIVATE_IPV4}:5000:5000  \
  -e "REGISTRY_STORAGE=s3" \
  -e "REGISTRY_STORAGE_S3_REGION=eu-west-1" \
  -e "REGISTRY_STORAGE_S3_BUCKET=docker-repo" \
  -e "REGISTRY_STORAGE_S3_ACCESSKEY=xxx" \
  -e "REGISTRY_STORAGE_S3_SECRETKEY=xxxxxxx" \
  registry:2

ExecStop=/usr/bin/docker stop docker-registry
```

**Comment by mindnuts** [comment]
Hi @stevvooe , yes the "Access denied" error was related to the wrongly configured bucket. The only issue which remains for me is that the docker container crashes successively and exits if i run it as a systemd unit file it runs correctly when run from the CLI. If i am not wrong the previous versions of regsitry used to play nice with systemd.

An [example](https://github.com/coreos/unit-examples/blob/master/docker-registry-s3/registry.3.service),  unit file for an older version of the registry. I can certainly run the older but deprecated version but i would like to take the benefit of the faster and better supported newer version of registry.

**Comment by dmp42** [comment]
@mindnuts does that command run correctly out of systemd?

Can you also check what's in the dead containers logs?

**Comment by mindnuts** [comment]
@dmp42 update, I tried the tag "registry:2.0.1" and it seems to be working :+1: 

not sure why registry:2 did not work. Anyways i would close this bug pending any other issue.

**Comment by mindnuts** [comment]
tag 2.0.1 seems to be working fine. Closing the issue.

**Comment by stevvooe** [comment]
@mindnuts This sounds like a slightly odd problem. Glad you've figured it out.

What could we do differently to play nice with systemd? As far as I understand, we do all the right things. Is it that it crashes with a bad configuration?
