### ISSUE TITLE
panics on all requests in master when resolving CloseNotifier

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#828]
It seems that every single request is panicking.

We can trigger with a simple curl call:

```$
curl -i http://localhost:5000/v2/
```

Here is a traceback with the panic handler disabled for clarity:

```
2015/08/06 14:46:04 http: panic serving [::1]:60089: the ResponseWriter does not implement CloseNotifier
goroutine 10 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xbb
github.com/docker/distribution/context.WithResponseWriter(0xb9fc98, 0xc20805af40, 0xb9fc60, 0xc20807c220, 0x0, 0x0, 0x0, 0x0)
	/Users/sday/go/src/github.com/docker/distribution/context/http.go:108 +0xdc
github.com/docker/distribution/registry/handlers.(*contextManager).context(0xc2080b4340, 0xb9e5e0, 0xc2080c0c80, 0xb9fc60, 0xc20807c220, 0xc20801f2b0, 0x0, 0x0)
	/Users/sday/go/src/github.com/docker/distribution/registry/handlers/context.go:133 +0x25c
github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc2080c0c80, 0xb9fc60, 0xc20807c220, 0xc20801f2b0)
	/Users/sday/go/src/github.com/docker/distribution/registry/handlers/app.go:396 +0xdd
github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0xb9d248, 0xc20802c008, 0xb9e810, 0xc2080c0c80, 0xb9fbb8, 0xc208101220, 0xc20801f2b0)
	/Users/sday/go/src/github.com/gorilla/handlers/handlers.go:88 +0x1be
github.com/gorilla/handlers.(*combinedLoggingHandler).ServeHTTP(0xc20800be00, 0xb9fbb8, 0xc208101220, 0xc20801f2b0)
	<autogenerated>:15 +0xbe
net/http.serverHandler.ServeHTTP(0xc208054a80, 0xb9fbb8, 0xc208101220, 0xc20801f2b0)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208101180)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

We need integration tests.

**Comment by stevvooe** [comment]
Updating gorilla fixed this: we should update this to only have a warning log message, rather than a full panic.
