### ISSUE TITLE
Support folders inside buckets for S3 storage backing

### ISSUE THREAD

**Issue by crazyfacka** [docker/distribution#915]
```bash
$ docker run \
-e REGISTRY_STORAGE=s3 \
-e REGISTRY_STORAGE_S3_ACCESSKEY=changeme \
-e REGISTRY_STORAGE_S3_SECRETKEY=changeme \
-e REGISTRY_STORAGE_S3_BUCKET=bucket/folder \
-e REGISTRY_STORAGE_S3_REGION=eu-west-1 \
-e REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR=redis \
-e REGISTRY_REDIS_ADDR=localhost:7240 \
-p 5000:5000 \
registry:2
```

The above command fails with these not so explicit logs:
```
panic: EOF

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f6402772e50, 0xc2080ee630, 0xc20808e360, 0x3, 0x0, 0x0, 0x0, 0x0, 0xc2080ee000, 0x0, ...)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:95 +0x64a
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:72 +0x523

goroutine 6 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 28 [runnable]:
net/http.(*persistConn).writeLoop(0xc2080af600)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
```

I've found out that this is due to having a slash in the bucket definition variable. Even escaping the slash does not work. Using a YAML file yields the same error.

Might be me, but I haven't found anywhere in the documentation that sub-folders are not supported.

Cheers!

**Comment by crazyfacka** [comment]
My bad for not reading properly the documentation. Skipped rootDirectory :(

**Comment by crazyfacka** [comment]
Apparently rootDirectory does works inside a registry created directory, and not as I thought it would. Is this really an issue?

**Comment by crazyfacka** [comment]
Again, capitalization error. I'm feeling kind of n00b a bit.
